on:
 push:
  branches:
   - master
name: Build and deploy Python app
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  # checkout the repo
  - uses: actions/checkout@master
  # setup python
  - name: Setup Python 3.7
    uses: actions/setup-python@v1
    with:
     python-version: 3.7
  # install dependencies
  - name: python install
    working-directory: Application
    run: |
     sudo apt install python3.7-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt 
  # Azure login
  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_CREDENTIALS }}
  - uses: azure/appservice-settings@v1
    with:
     app-name: vivekflask1
     general-settings-json: '{"linuxFxVersion": "PYTHON|3.7"}' #'General configuration settings as Key Value pairs'
  # deploy web app
  - uses: azure/webapps-deploy@v1
    with:
     app-name: vivekbottle1
     package: Application
  # Azure logout
  - name: logout
    run: |
     az logout
